#!/usr/bin/env bash
# The script accepts a string as an argument
# Display Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# Ping the IP 5 times
if [ "$#" -eq 1 ]
then
    ping -c 5 "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
