#!/usr/bin/env bash
# Changes the following domain resolve IPs:
#   localhost from 127.0.0.1 to 127.0.0.2
#   facebook.com from 157.240.11.35 to 8.8.8.8

# Copy the /etc/hosts file to a temporary file
cp /etc/hosts ~/hosts.new

# Change the IP of localhost to 127.0.0.2
sed -i '' 's/127.0.0.1/127.0.0.2/' ~/hosts.new

# Change the IP of facebook.com to 8.8.8.8
sed -i '' 's/157.240.11.35/8.8.8.8/' ~/hosts.new

# Replace the original /etc/hosts file with the modified one
sudo cp -f ~/hosts.new /etc/hosts
