#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# Create a backup of the /etc/hosts file
sudo cp /etc/hosts ~/"$(date +%s)_hosts_backup"

# Add new entries to the /etc/hosts file
echo "127.0.0.2	localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
